### ISSUE TITLE
Deploy contract screenshot

### ISSUE THREAD

**Issue by camiinthisthang** [womenbuildweb3/30daysofweb3.xyz#30]
<img width="963" alt="Screen Shot 2022-07-16 at 7 14 12 PM" src="https://user-images.githubusercontent.com/15346823/179375210-bc843162-dcf0-4337-a9ed-2ca85a3fde7a.png">

**Comment by Krish-bhardwaj** [comment]
Hi i am also a part of this 30day session can you tell me what is this issue ? can i contribute to this opensource project ?
